services:
  nextjs:
    container_name: tournament-next
    restart: unless-stopped
    build:
      context: .
      dockerfile: next.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - tournament-network

  database:
    image: postgres:latest
    container_name: tournament-db
    restart: unless-stopped
    ports:
      - "5432:${PG_PORT}"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - databaseData:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - tournament-network

  adminer:
    image: adminer:latest
    container_name: tournament-adminer
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - tournament-network
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: "pgsql"
      ADMINER_DEFAULT_DB_HOST: tournament-db
      ADMINER_DEFAULT_DB_NAME: ${PG_DATABASE}
    command: php -S 0.0.0.0:8080 -t /var/www/html

  nginx:
    image: nginx:alpine
    container_name: tournament-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - nextjs
      - adminer
    networks:
      - tournament-network

volumes:
  databaseData:

networks:
  tournament-network:
    driver: bridge