services:
  database:
    image: postgres:latest
    container_name: tournament-db
    ports:
      - "5432:${PG_PORT}"
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - databaseData:/var/lib/postgresql/data

  nextjs:
    container_name: tournament-next
    image: user/next:latest
    build:
      context: .
      dockerfile: next.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: "pgsql"
      ADMINER_DEFAULT_DB_HOST: tournament-db
      ADMINER_DEFAULT_DB_NAME: ${PG_DATABASE}
    command: php -S 0.0.0.0:8080 -t /var/www/html

volumes:
  databaseData:
